@baseUrl = https://localhost:7323/auth
@token = very_secret_key_that_should_be_long_and_secure

POST {{baseUrl}}/login
content-type: application/json

{
    "username": "admin@localhost",
    "password": "Admin@123"
}

###

POST {{baseUrl}}/subscribe
content-type: application/json

{
    "lastname": "Doe",
    "firstname": "John",
    "email": "john.doe@localhost",
    "password": "Zsw21qa!"
}

###
 GET https://localhost:7323/health
